[package]
name = "vae"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.22.2"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }
